# ⚠️ Only non-root builds (Can be used on rooted device).

[YT] # Default patches are applied, Exception for lines 4 & 5 :
included-patches = "'Custom branding icon for YouTube' 'Visual preferences icons'"
excluded-patches = "'Custom branding name for YouTube' 'Swipe controls'"
# patcher-args = "-e 'Custom branding icon for YouTube' -appIcon=xisr_yellow -e 'Custom header for YouTube' -customHeader=xisr_yellow -e 'Translations for YouTube' -selectedTranslations=fr-rFR -selectedStringResources=fr"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music] # Default patches are applied, Exception for lines 10 & 11 :
included-patches = "'Custom branding icon for YouTube Music' 'Custom header for YouTube Music'"
excluded-patches = "'Custom branding name for YouTube Music'"
# patcher-args = "-e 'Custom branding icon for YouTube Music' -appIcon=xisr_yellow -e 'Custom header for YouTube Music' -customHeader=xisr_yellow"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
