# ⚠️ Only non-root builds (Can be used on rooted device).

[YT] # Default patches are applied, Exception for lines 4 & 5 :
included-patches = "'Custom branding icon for YouTube' 'Visual preferences icons'"
excluded-patches = "'Custom branding name for YouTube' 'Swipe controls'"
patcher-args = "--legacy-options options.json"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music] # Default patches are applied, Exception for lines 10 & 11 :
included-patches = "'Custom branding icon for YouTube Music' 'Custom header for YouTube Music'"
excluded-patches = "'Custom branding name for YouTube Music'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
patcher-args = "--legacy-options options.json"
arch = "arm64-v8a"
